# Generated by Django 5.1.4 on 2024-12-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('work_experience', models.IntegerField()),
                ('department', models.CharField(max_length=50)),
                ('group_id', models.IntegerField()),
            ],
        ),
    ]
